version: "1"

volumes:
  pg_hack_data:

services:
  postgresql:
    image: postgres:14
    ports:
      - 15432:5432
    container_name: postgres_dash
    volumes:
      - pg_hack_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: postgres
  cache:
    image: redis:6.2.5
    ports:
      - 16379:6379
    container_name: redis_dash
